# -*- coding: utf-8 -*-
"""Texas_tech_market_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-7kYHP4sCb0CWV2iIjOo3YU-rjT2g8p

Initial Libraries
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

"""Multi Role Scraper"""

import requests
import pandas as pd
import time

# Define the roles you want to track
target_roles = [
    "Data Scientist",
    "Data Analyst",
    "Data Engineer",
    "Machine Learning Engineer",
    "Analytics Engineer"
]

location = "Dallas, TX"

all_jobs = []
# Updated to include major Texas tech hubs
locations = ["Dallas, TX", "Austin, TX", "Houston, TX", "Irving, TX", "Plano, TX"]
categories = ["Data and Analytics", "Software Engineering", "Science and Engineering"]

for loc in locations:
    for cat in categories:
        # Loop through the first 5 pages for each combination
        for page in range(0, 5):
            print(f"Scraping {cat} in {loc} | Page {page}...")
            url = f"https://www.themuse.com/api/public/jobs?category={cat}&location={loc}&page={page}"

            try:
                response = requests.get(url)
                results = response.json().get('results', [])

                if not results: # Break if we hit a page with no more jobs
                    break

                for job in results:
                    all_jobs.append({
                        'job_title': job['name'],
                        'company': job['company']['name'],
                        'location': loc,
                        'category': cat,
                        'level': job['levels'][0]['name'] if job['levels'] else 'Entry',
                        'date_posted': job['publication_date']
                    })
                time.sleep(0.5) # Fast but respectful
            except:
                break

df_jobs = pd.DataFrame(all_jobs)
df_jobs.drop_duplicates(subset=['job_title', 'company'], inplace=True)
print(f"Total Unique Jobs: {len(df_jobs)}")

"""Connecting to Neon"""

!pip install psycopg2-binary sqlalchemy

from sqlalchemy import create_engine

db_url = "postgresql://neondb_owner:npg_HVJCj3Qdxvn6@ep-withered-butterfly-amli99cx-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

engine = create_engine(db_url)

try:
    df_jobs.to_sql('raw_jobs', engine, if_exists='replace', index=False)
    print("Success! Your data is now in the cloud database.")
except Exception as e:
    print(f"Error: {e}")

